### ISSUE TITLE
Not working on Vagrant 1.5.0 -- undefined method `scope' for #<Vagrant::UI::Colored:0x0000010133ecb0> (NoMethodError)

### ISSUE THREAD

**Issue by c10l** [schubergphilis/vagrant-chef-zero#41]
Hey,

Just to give a heads up that since I upgraded Vagrant to 1.5 I'm getting this error:

```
/Users/cassiano/.vagrant.d/gems/gems/vagrant-chef-zero-0.6.0/lib/vagrant-chef-zero/env.rb:13:in `initialize': undefined method `scope' for #<Vagrant::UI::Colored:0x0000010133ecb0> (NoMethodError)
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-chef-zero-0.6.0/lib/vagrant-chef-zero/action.rb:37:in `new'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-chef-zero-0.6.0/lib/vagrant-chef-zero/action.rb:37:in `block in chef_zero_ui_setup'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-chef-zero-0.6.0/lib/vagrant-chef-zero/action.rb:36:in `tap'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-chef-zero-0.6.0/lib/vagrant-chef-zero/action.rb:36:in `chef_zero_ui_setup'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-chef-zero-0.6.0/lib/vagrant-chef-zero/plugin.rb:15:in `reconfig'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:45:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:45:in `block (2 levels) in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:44:in `tap'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:44:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:43:in `map'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:43:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/environment.rb:300:in `hook'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/environment.rb:141:in `initialize'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.0/bin/vagrant:138:in `new'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.0/bin/vagrant:138:in `<main>'
```
